name: Infrastructures Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: true
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        continue-on-error: true
        run: |
          terraform plan -detailed-exitcode
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 2 ]; then
            echo "Terraform detected changes."
            echo "::set-output name=terraform_exit_code::2"
          elif [ $EXIT_CODE -eq 1 ]; then
            echo "Terraform encountered an error."
            echo "::set-output name=terraform_exit_code::1"
          else
            echo "No changes detected."
            echo "::set-output name=terraform_exit_code::0"
          fi

      - name: Conditional Actions Based on Terraform Plan
        if: steps.terraform-plan.outputs.terraform_exit_code == '1'
        run: echo "Terraform failed with an error!"
        continue-on-error: false

      - name: Proceed if Changes Were Detected
        if: steps.terraform-plan.outputs.terraform_exit_code == '2'
        run: echo "Proceeding with changes detected by Terraform."

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: success() && needs.terraform_plan.outputs.terraform_exit_code == '2'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

    environment:
      name: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve=true